# Homebrew
- name: Tap a Homebrew repository, state present
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop:
    - homebrew/cask-drivers
    - homebrew/cask-fonts

- name: Update homebrew
  community.general.homebrew:
    upgrade_all: yes
    update_homebrew: yes

- name: Install linked brew packages
  community.general.homebrew:
    name: "{{ config.brew.linked_packages }}"
    state: linked

- name: Install brew packages
  community.general.homebrew:
    name: "{{ config.brew.packages }}"
    state: present

- name: Install brew casks
  community.general.homebrew_cask:
    name: "{{ config.brew.casks }}"
    state: present
